//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enigma_intergrate_p1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelingDetail
    {
        public int ChannelingID { get; set; }
        public string DoctorName { get; set; }
        public string HospitalName { get; set; }
        public string TimeSlot { get; set; }
        public string PatientID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
