//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enigma_intergrate_p1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int ID { get; set; }
        public string NID { get; set; }
        public string HospitalName { get; set; }
    }
}
