//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enigma_intergrate_p1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        public string PID { get; set; }
        public string PharmacyName { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
    }
}
